version: '3.8'

services:
  server:
    build: .
    container_name: heritage_server
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=heritage
      - MYSQL_PASSWORD=heritage123
      - MYSQL_DATABASE=heritage_tour
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

  mysql:
    image: mysql:8.0
    container_name: heritage_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: heritage_tour
      MYSQL_USER: heritage
      MYSQL_PASSWORD: heritage123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: heritage_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: